spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarymgmentdb
    username: root
    password: mysqlpsswd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
jwt:
  secretkey: ()_arO?MX=&m2dsqi+Zlu=,KE@7fJnZB}ytj.y,YK?|
  expiration: 14400000